version: '3.9'

services:
  prod:
    container_name: ytc-frontend-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './:app'
      - '/app/node_modules'
    ports:
      - 80:80
      - "8000:8000"